name: Compile & MTR

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '**.md'
      - 'scripts/setup/**'
      - '.devcontainer/**'
  pull_request:
    paths-ignore:
      - 'Docs/**'
      - 'website/**'
      - '**.md'
      - 'scripts/**'
      - 'install_scripts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  PROTOC: protoc


jobs:
  stonedb-build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      
      - name: install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install cmake make perl bison libaio-dev \
          openssl libssl-dev libncurses5-dev libreadline-dev \
          autoconf automake libtool \
          libreadline-dev libpam0g-dev zlib1g-dev libcurl-ocaml-dev \
          autotools-dev libicu-dev libboost-all-dev \
          libgflags-dev libsnappy-dev libbz2-dev liblz4-dev libzstd-dev libjemalloc-dev -y
          
      - name: install libs
        run: |
          ls
       
